### ISSUE TITLE
PGLock needs tuning

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/vector-forge#35]
```
No handlers could be found for logger "sqlalchemy.pool.QueuePool"
Failed during the creation of tile None
No handlers could be found for logger "sqlalchemy.pool.QueuePool"
Traceback (most recent call last):
  File "scripts/mvt_tiler.py", line 266, in <module>
    main()
  File "scripts/mvt_tiler.py", line 250, in main
    pm.imap_unordered(tileGrid, createTile, 50, callback=callback)
  File "/home/tileforge/vector-forge/.venv/local/lib/python2.7/site-packages/poolmanager-0.0.4-py2.7.egg/poolmanager/__init__.py", line 57, in imap_unordered
    raise Exception(e)
Exception: (TransactionRollbackError) canceling statement due to conflict with recovery
DETAIL:  User was holding a relation lock for too long.
```

Here are some possible answers:
http://stackoverflow.com/questions/14592436/postgresql-error-canceling-statement-due-to-conflict-with-recovery

http://www.postgresql.org/docs/current/static/hot-standby.html#HOT-STANDBY-CONFLICT

**Comment by ltclm** [comment]
That's a known issue on our replication slaves.
To avoid this problem we have to add the following configuration to the replication slaves:
```
# https://github.com/geoadmin/deploy/issues/6
max_standby_streaming_delay = 10min
max_standby_archive_delay = 10min
```

camp2camp has replaced the small instance with two bigger ones yesterday. I patched the configuration of these instances manually. It should work now.

@danduk82 do you see any option to have a slightly modified replication slave configuration.

**Comment by loicgasser** [comment]
@ltclm thanks for the info. I'm testing I'll let you know.

**Comment by loicgasser** [comment]
https://github.com/geoadmin/deploy/issues/6

**Comment by loicgasser** [comment]
It's commented again ;) Puppet is evil
